// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCprWbNkBlUsK_QVjA_BV6gR1A5AIFM3os',
    appId: '1:546594028173:web:1a7f127ab98e083de9c0c4',
    messagingSenderId: '546594028173',
    projectId: 'mystore-7f613',
    authDomain: 'mystore-7f613.firebaseapp.com',
    databaseURL: 'https://mystore-7f613-default-rtdb.firebaseio.com',
    storageBucket: 'mystore-7f613.appspot.com',
    measurementId: 'G-NVCX0TVTWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1IxyiBdN3xfx1nGNiXeOoGjI61sMjYw',
    appId: '1:546594028173:android:632c1a14667db8eee9c0c4',
    messagingSenderId: '546594028173',
    projectId: 'mystore-7f613',
    databaseURL: 'https://mystore-7f613-default-rtdb.firebaseio.com',
    storageBucket: 'mystore-7f613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl4Dy2krfSAU7tCUyAHBRjTSPDEdfzqto',
    appId: '1:546594028173:ios:7288f020a43f130ce9c0c4',
    messagingSenderId: '546594028173',
    projectId: 'mystore-7f613',
    databaseURL: 'https://mystore-7f613-default-rtdb.firebaseio.com',
    storageBucket: 'mystore-7f613.appspot.com',
    iosBundleId: 'com.jonathan.app478',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl4Dy2krfSAU7tCUyAHBRjTSPDEdfzqto',
    appId: '1:546594028173:ios:7288f020a43f130ce9c0c4',
    messagingSenderId: '546594028173',
    projectId: 'mystore-7f613',
    databaseURL: 'https://mystore-7f613-default-rtdb.firebaseio.com',
    storageBucket: 'mystore-7f613.appspot.com',
    iosBundleId: 'com.jonathan.app478',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCprWbNkBlUsK_QVjA_BV6gR1A5AIFM3os',
    appId: '1:546594028173:web:2fdbec1885d4a170e9c0c4',
    messagingSenderId: '546594028173',
    projectId: 'mystore-7f613',
    authDomain: 'mystore-7f613.firebaseapp.com',
    databaseURL: 'https://mystore-7f613-default-rtdb.firebaseio.com',
    storageBucket: 'mystore-7f613.appspot.com',
    measurementId: 'G-EQGDLXRXET',
  );
}
